User.create!([
  {email: "sadtrashhobo@yahoo.com", password: "password", encrypted_password: "$2a$10$UQXDgTH6b7zDXMWjXCYCLuAqvzw5xae3JlDxEi5yEj296.MjnvPGm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 9, current_sign_in_at: "2014-05-24 16:09:52", last_sign_in_at: "2014-05-24 14:47:47", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"},
  {email: "budapest4evs@gmail.com", password: "password", encrypted_password: "$2a$10$BcCRibsLi5FC7ZA.N4XH4ujs/VXMvqu3.aVe9GgHH9dNQpY2TPy96", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 7, current_sign_in_at: "2014-05-24 13:05:25", last_sign_in_at: "2014-05-24 11:08:40", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"},
  {email: "aporrosenpai@orimposu.net", password: "password", encrypted_password: "$2a$10$w3wI93YEZDuFy7d6hLIkZeGTWj1ffxCO0UjpLKAS5crItHFwFvHU2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 6, current_sign_in_at: "2014-05-24 14:24:55", last_sign_in_at: "2014-05-24 14:08:24", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"},
  {email: "themusesnine@orimposu.net", password: "password", encrypted_password: "$2a$10$EYTlckY8GHst8vB62mE5vOK5vdBtvz.DG44tX/HuBw6jQcSayHUn6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2014-05-24 08:52:44", last_sign_in_at: "2014-05-24 08:52:44", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"}
])
Frit.create!([
  {prompt: "rivalry", limit: "6 word", content: "Nobody knows who you are, Helios", user_id: 3, posted_on: "2014-05-23 17:42:02"},
  {prompt: "a grandfather clock", limit: "5 word", content: "This is getting really old", user_id: 1, posted_on: "2014-05-24 07:44:40"},
  {prompt: "the hottest summer on record", limit: "5 word", content: "Sorry, that was my fault.", user_id: 3, posted_on: "2014-05-24 13:30:02"},
  {prompt: "the illegitimate son of a king", limit: "1 sentence", content: "Did you mean my life.", user_id: 3, posted_on: "2014-05-24 14:12:40"},
  {prompt: "rivalry", limit: "3 sentence", content: "l.o.l.", user_id: 1, posted_on: "2014-05-24 16:15:07"}
])
Limit.create!([
  {limit: "6 word"},
  {limit: "5 word"},
  {limit: "1 sentence"},
  {limit: "2 sentence"},
  {limit: "3 sentence"}
])
Prompt.create!([
  {topic: "dinosaurs"},
  {topic: "wings"},
  {topic: "fear"},
  {topic: "sacrifice"},
  {topic: "diamonds"},
  {topic: "a music box"},
  {topic: "church"},
  {topic: "rivalry"},
  {topic: "a split personality"},
  {topic: "social class"},
  {topic: "a moon"},
  {topic: "a rescue"},
  {topic: "a grandfather clock"},
  {topic: "a curse"},
  {topic: "an escape"},
  {topic: "blackmail"},
  {topic: "a transformation"},
  {topic: "a book"},
  {topic: "revenge"},
  {topic: "mirrors"},
  {topic: "twins"},
  {topic: "an old photograph"},
  {topic: "slavery"},
  {topic: "a discovery"},
  {topic: "cries in the night"},
  {topic: "a cat"},
  {topic: "forbidden love"},
  {topic: "a pursuit"},
  {topic: "blindness"},
  {topic: "blood"},
  {topic: "a lock of hair"},
  {topic: "disease"},
  {topic: "betrothal"},
  {topic: "a tomb"},
  {topic: "a dragon"},
  {topic: "an exotic perfume"},
  {topic: "a test"},
  {topic: "a ship"},
  {topic: "a riddle"},
  {topic: "a time machine"},
  {topic: "body paint"},
  {topic: "an amulet"},
  {topic: "a reluctant hero"},
  {topic: "a siren"},
  {topic: "a monster"},
  {topic: "darkness"},
  {topic: "rogues"},
  {topic: "a psychopath"},
  {topic: "a reluctant villain"},
  {topic: "a vigilante"},
  {topic: "betrayal"},
  {topic: "redemption"},
  {topic: "a bet"},
  {topic: "failed marriages"},
  {topic: "the future"},
  {topic: "a vacation disaster"},
  {topic: "a genie that got stuck in an urn instead"},
  {topic: "things under your bed"},
  {topic: "your second favorite skeleton in the closet"},
  {topic: "the apocalypse"},
  {topic: "where bad dreams go during lunch time"},
  {topic: "death taking a coffee break"},
  {topic: "cannibalism"},
  {topic: "baby godzilla"},
  {topic: "your reflection, if it was sentient"},
  {topic: "a habit of decomposing"},
  {topic: "amnesia"},
  {topic: "a failed business venture"},
  {topic: "suddenly gaining psychic abilities"},
  {topic: "the night before a wedding"},
  {topic: "an incurable epidemic"},
  {topic: "a second honeymoon"},
  {topic: "a broken promise"},
  {topic: "incessant hallucinations"},
  {topic: "the hottest summer on record"},
  {topic: "a runaway"},
  {topic: "too many cups of coffee"},
  {topic: "a failed bank heist"},
  {topic: "New Year's Eve"},
  {topic: "a disapproving family"},
  {topic: "a prophecy"},
  {topic: "winning the Nobel Prize"},
  {topic: "waiting for two thousand years"},
  {topic: "a crisis of faith"},
  {topic: "the last week before your retirement"},
  {topic: "your last week to live"},
  {topic: "a lightning strike"},
  {topic: "prolonged exposure to radiation"},
  {topic: "being on the run from federal agents"},
  {topic: "not bathing for an entire year"},
  {topic: "election night"},
  {topic: "misreading an email"},
  {topic: "moving across the country"},
  {topic: "accidentally starting a forest fire"},
  {topic: "being fired"},
  {topic: "a case of mistaken identity"},
  {topic: "a disastrous job interview"},
  {topic: "a witch's spell"},
  {topic: "being left at the altar"},
  {topic: "adopting three children"},
  {topic: "getting disowned"},
  {topic: "a prison break"},
  {topic: "a sassy nun"},
  {topic: "a gold digger"},
  {topic: "a computer hacker"},
  {topic: "the weather"},
  {topic: "an ugly duchess"},
  {topic: "a fallen angel"},
  {topic: "a prodigy"},
  {topic: "the illegitimate son of a king"},
  {topic: "a plus-size model"},
  {topic: "a comic book collector"},
  {topic: "a former child television star"},
  {topic: "a clumsy gymnast"},
  {topic: "an unsuccessful comedian"},
  {topic: "one half of a husband-and-wife crime-fighting duo"},
  {topic: "a single mother of three"},
  {topic: "a freelance assassin"},
  {topic: "a pregnant astronaut"},
  {topic: "an old lady with twenty cats"},
  {topic: "a tactless diplomat"},
  {topic: "the ghost of Ernest Hemingway"},
  {topic: "a parallel universe"},
  {topic: "getting trapped in a parallel universe"},
  {topic: "take on a new identity"},
  {topic: "joining an underground militia"},
  {topic: "stealing a baby"},
  {topic: "the real murderer of JFK"},
  {topic: "making a deal with the devil"},
  {topic: "a very important phone call"},
  {topic: "developing short-term memory loss"},
  {topic: "discovering plans for an impending alien invasion"},
  {topic: "developing the ability to fly"},
  {topic: "flight"},
  {topic: "accidentally running over the family dog"},
  {topic: "a blind date"},
  {topic: "a lifelike android"},
  {topic: "getting trapped inside a popular TV show"},
  {topic: "joining the mafia"},
  {topic: "a message from God"},
  {topic: "a Vegas wedding"},
  {topic: "vengeful spirits"},
  {topic: "the fountain of youth"},
  {topic: "zombies"},
  {topic: "a buried atomic bomb"},
  {topic: "World War III"},
  {topic: "arson"},
  {topic: "a family of robots"},
  {topic: "a 17-century treasure map"},
  {topic: "Russian roulette"},
  {topic: "the perfect murder"},
  {topic: "an accidental kiss"},
  {topic: "getting mistaken for royalty"},
  {topic: "a runaway royalty and a confused commoner "},
  {topic: "pirates"},
  {topic: "a man with a robotic arm"},
  {topic: "childhood friends"},
  {topic: "accidentally hugging the wrong person from behind"},
  {topic: "the selfie generation"},
  {topic: "banana fritters"},
  {topic: "partners in a dance class"},
  {topic: "a pyromaniac"},
  {topic: "two brothers on a road trip"},
  {topic: "the Home Shopping Network"},
  {topic: "late-night infomercials"},
  {topic: "the Grim Reaper's day off"},
  {topic: "a merman washing up on shore"}
])
